clc,clear


casename = 'bi_air';
ref_val = 1e-6;
save_figs = 0;
cmap = slanCM('bupu');

% % r_optimization, sor (all cases)
% address_list = {'../r_optimization/sor/r08/',...
%                 '../r_optimization/sor/r10/',...
%                 '../r_optimization/sor/r12/',...
%                 '../r_optimization/sor/r14/',...
%                 '../r_optimization/sor/r16/',...
%                 '../r_optimization/sor/r18/',...
%                 '../r_optimization/sor/r182/',...
%                 '../r_optimization/sor/r184/',...
%                 '../r_optimization/sor/r186/',...
%                 '../r_optimization/sor/r188/',...
%                 '../r_optimization/sor/r20/',...
%                 '../r_optimization/sor/r22/',...
%                 '../r_optimization/sor/gs/'};
% lgds = {'$r = 0.8$','$r = 1.0$','$r = 1.2$','$r = 1.4$','$r = 1.6$',...
%         '$r = 1.8$','$r = 1.82$','$r = 1.84$','$r = 1.86$','$r = 1.88$',...
%         '$r = 2.0$','$r = 2.2$','GS'};
% linestyles = {'-','-',':','-.','-','--',':','-.','-','--',':','-.','--'};

% r_optimization, sor (selected cases)
address_list = {'../r_optimization/sor/r08/',...
                '../r_optimization/sor/r10/',...
                '../r_optimization/sor/r16/',...
                '../r_optimization/sor/r18/',...
                '../r_optimization/sor/r20/',...
                '../r_optimization/sor/gs/'};
lgds = {'$r = 0.8$','$r = 1.0$','$r = 1.6$',...
        '$r = 1.8$',...
        '$r = 2.0$','GS'};
linestyles = {'-','-','--',':','-.','--'};
xlims = [0,2000];
ylims = [0,1e5];
filename = 'r_optimization_sor';

% % r_optimization, slor (all cases)
% address_list = {'../r_optimization/slor/r08/',...
%                 '../r_optimization/slor/r10/',...
%                 '../r_optimization/slor/r12/',...
%                 '../r_optimization/slor/r14/',...
%                 '../r_optimization/slor/r16/',...
%                 '../r_optimization/slor/r18/',...
%                 '../r_optimization/slor/r182/',...
%                 '../r_optimization/slor/r184/',...
%                 '../r_optimization/slor/r186/',...
%                 '../r_optimization/slor/r188/',...
%                 '../r_optimization/slor/r20/',...
%                 '../r_optimization/slor/r22/',...
%                 '../r_optimization/slor/lgs/'};
% lgds = {'$r = 0.8$','$r = 1.0$','$r = 1.2$','$r = 1.4$','$r = 1.6$',...
%         '$r = 1.8$','$r = 1.82$','$r = 1.84$','$r = 1.86$','$r = 1.88$',...
%         '$r = 2.0$','$r = 2.2$','LGS'};
% linestyles = {'-','-',':','-.','-','--',':','-.','-','--',':','-.','--'};

% % r_optimization, slor (selected cases)
% address_list = {'../r_optimization/slor/r08/',...
%                 '../r_optimization/slor/r10/',...
%                 '../r_optimization/slor/r16/',...
%                 '../r_optimization/slor/r18/',...
%                 '../r_optimization/slor/r20/',...
%                 '../r_optimization/slor/lgs/'};
% lgds = {'$r = 0.8$','$r = 1.0$','$r = 1.6$',...
%         '$r = 1.8$',...
%         '$r = 2.0$','LGS'};
% linestyles = {'-','-','--',':','-.','--'};
% xlims = [0,2000];
% ylims = [0,1e5];
% filename = 'r_optimization_slor';

% % res_comparison
% address_list = {'../res_comparison/pj/',...
%                 '../res_comparison/gs/',...
%                 '../res_comparison/sor/',...
%                 '../res_comparison/lgs/',...
%                 '../res_comparison/slor/'};
% lgds = {'PJ','GS','SOR','LGS','SLOR'};
% linestyles = {'-','-','--',':','-.'};
% xlims = [0,16000];
% ylims = [0,1e5];
% filename = 'res_log_comparison';


colors = config_colors_cmap(length(address_list),cmap,1);


fontsize = 14;
lnwdth = 1.5;
pos = [1000,500];
pba = [2,1];

%% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

figure(1),clf,grid on,hold on
for i = 1:length(address_list)
  res =readmatrix([address_list{i},casename,'.log'],'filetype','delimitedtext');

  plot(0:(length(res)-1),res,'color',colors{i},'linestyle',linestyles{i},...
          'displayname',lgds{i},'linewidth',lnwdth)
  % plot(0:(length(res)-1),res,'displayname',lgds{i})

  fprintf("%s: iter %d\n",lgds{i},find(res<ref_val,1));

end

set(gca,'yscale','log')

xylabel_latex('n','|L\phi|_{max}');
set_fontsize_position(fontsize,pos,pba);
lgd = legend();
lgd_latex(legend())
xlim(xlims)
ylim(ylims)

set_rndrr_painters();

if save_figs
  save_fig_eps(filename);
end

%% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

