function f_orthogonality_eom(address,casename,filename)

disp(filename{1})
disp([address,casename,filename{1}])
mesh_x = dlmread([address,casename,filename{1}]);
mesh_y = dlmread([address,casename,filename{2}]);

B = zeros(size(mesh_x));

for j = 2:size(mesh_x,1)-1
  B(j,1) = uniform_scheme_der1_o2_central_prdc_ksi(mesh_x,j)*...
           uniform_scheme_der1_o2_central(mesh_x,1,j,2) + ...
           uniform_scheme_der1_o2_central_prdc_ksi(mesh_y,j)*...
           uniform_scheme_der1_o2_central(mesh_y,1,j,2);
end

B(1,1) = uniform_scheme_der1_o2_central_prdc_ksi(mesh_x,1)*...
         uniform_scheme_der1_o2_forward(mesh_x,1,1,2) + ...
         uniform_scheme_der1_o2_central_prdc_ksi(mesh_y,1)*...
         uniform_scheme_der1_o2_forward(mesh_y,1,1,2);

B(end,1) = uniform_scheme_der1_o2_central_prdc_ksi(mesh_x,size(mesh_x,1))*...
           uniform_scheme_der1_o2_backward(mesh_x,1,size(mesh_x,1),2) + ...
           uniform_scheme_der1_o2_central_prdc_ksi(mesh_y,size(mesh_x,1))*...
           uniform_scheme_der1_o2_backward(mesh_y,1,size(mesh_x,1),2);

for i = 2:size(mesh_x,2)-1
  B(1,i) = uniform_scheme_der1_o2_central(mesh_x,i,1,1)*...
           uniform_scheme_der1_o2_forward(mesh_x,i,1,2) + ...
           uniform_scheme_der1_o2_central(mesh_y,i,1,1)*...
           uniform_scheme_der1_o2_forward(mesh_y,i,1,2) ;

  B(end,i) = uniform_scheme_der1_o2_central(mesh_x,i,size(mesh_x,1),1)*...
             uniform_scheme_der1_o2_backward(mesh_x,i,size(mesh_x,1),2) + ...
             uniform_scheme_der1_o2_central(mesh_y,i,size(mesh_x,1),1)*...
             uniform_scheme_der1_o2_backward(mesh_y,i,size(mesh_x,1),2);

end

for j = 2:size(mesh_x,1)-1
  for i = 2:size(mesh_x,2)-1
    B(j,i) = uniform_scheme_der1_o2_central(mesh_x,i,j,1)*...
             uniform_scheme_der1_o2_central(mesh_x,i,j,2) + ...
             uniform_scheme_der1_o2_central(mesh_y,i,j,1)*...
             uniform_scheme_der1_o2_central(mesh_y,i,j,2);
  end
end


norm_total = sqrt(sum(sum(B(:,1:end-1).^2)));
norm_airfoil = sqrt(sum(sum(B(1,1:end-1).^2)));

fprintf("total: %e\n",norm_total)
fprintf("airfoil: %e\n",norm_airfoil)

end